FROM python:3.7


WORKDIR /usr/src/app


ENV AZURE_CONNECTION_STRING ${AZURE_CONNECTION_STRING}
ENV ODOO_URL ${ODOO_URL}
ENV ODOO_USER ${ODOO_URL}
ENV ODOO_PASSWORD ${ODOO_PASSWORD}
ENV ODOO_DATABASE ${ODOO_DATABASE}
ENV UPDATE_SHEET_CONTAINER ${UPDATE_SHEET_CONTAINER}
ENV UPDATE_SHEET_FILE_NAME ${UPDATE_SHEET_FILE_NAME}
ENV SLACK_URL ${SLACK_URL}

COPY ./requirements.txt ./
RUN pip install -r requirements.txt


COPY ./src/ ./


CMD ["python", "./main.py"]



