version: "3"

services: 
    importer:
        build: .
        environment: 
            - AZURE_CONNECTION_STRING=${AZURE_CONNECTION_STRING}
            - ODOO_URL=${ODOO_URL}
            - ODOO_USER=${ODOO_USER}
            - ODOO_PASSWORD=${ODOO_PASSWORD}
            - ODOO_DATABASE=${ODOO_DATABASE}
            - EMPLOYEE_MASTER_SHEET_CONTAINER=${EMPLOYEE_MASTER_SHEET_CONTAINER}
            - EMPLOYEE_MASTER_SHEET_FILE_NAME=${EMPLOYEE_MASTER_SHEET_FILE_NAME}
            - UPDATE_SHEET_CONTAINER=${UPDATE_SHEET_CONTAINER}
            - UPDATE_SHEET_FILE_NAME=${UPDATE_SHEET_FILE_NAME}
            - ORG_SHEET_CONTAINER=${ORG_SHEET_CONTAINER}
            - ORG_SHEET_FILE_NAME=${ORG_SHEET_FILE_NAME}